// @flow

export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';

export const LOAD_CLUB = 'LOAD_CLUB';
export const LOAD_CLUB_SUCCESS = 'LOAD_CLUB_SUCCESS';
export const LOAD_CLUB_FAILED = 'LOAD_CLUB_FAILED';

export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const CREATE_CLUB = 'CREATE_CLUB';
export const CREATE_CLUB_SUCCESS = 'CREATE_CLUB_SUCCESS';
export const CREATE_CLUB_FAILED = 'CREATE_CLUB_FAILED';

export const SET_GROWLER = 'SET_GROWLER';

export const SEARCH_BOOK_SUCCESS = 'SEARCH_BOOK_SUCCESS';
export const DELETE_BOOK = 'DELETE_BOOK';
export const CONFIRM_BOOK = 'CONFIRM_BOOK';
export const INVITE_MEMBER = 'INVITE_MEMBER';

export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED';
export const GET_MESSAGES = 'GET_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
